[package]
name = "trust"
version = "0.1.0"
authors = ["makyos <makyos@gmail.com>"]
edition = "2018"

[dependencies]
twitter-stream = "0.9"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.34"
regex = "1.3.1"